<div id="accordion3" class="accordion">
    <h2>Ejercicio 7.3 - Accordion</h2>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>AAA</h4>
        </div>
    </div>
    <div data-role="content">
        <p>aaa</p>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>BBB</h4>
        </div>
    </div>
    <div data-role="content">
        <p>bbb</p>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>CCC</h4>
        </div>
    </div>
    <div data-role="content">
        <p>ccc</p>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#accordion3": {
            "accordion": {
            "active": [],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
            }
        }
    }
</script>
