<div id="modal" class="accordion">
    <h2>Ejercicio 7.3 - Modal</h2>
    <button type="button" class="action" data-trigger="trigger">
        <span data-bind="i18n: 'Click Here'"></span>
    </button>
    <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Ejercicio 7.3 - Modal',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
        <div class="content">
            Este es el modal del ejercicio 7.3
        </div>
    </div>
</div>
