<div id="accordion" class="accordion" data-mage-init='{
        "accordion":{
            "active": [],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <h2>Accordion using the 'data-mage-init' attribute </h2>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Diego</h4>
        </div>
    </div>
    <div data-role="content">
        <img src="https://cdn.britannica.com/76/124976-050-E03E50CE/Diego-Maradona-1986.jpg" alt="Diego" width="300"
             height="400">
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Armando</h4>
        </div>
    </div>
    <div data-role="content">
        <img
            src="https://conteudo.imguol.com.br/c/esporte/2e/2020/04/29/maradona-na-conquista-da-copa-do-mundo-fifa-de-1986-apos-o-episodio-da-la-mano-de-dios-1588180936935_v2_450x600.jpg"
            alt="Diego2" width="300" height="400">
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Maradona</h4>
        </div>
    </div>
    <div data-role="content">
        <img src="https://www.telam.com.ar/thumbs/bluesteel/advf/imagenes/2020/11/5fbe9bdadc9bb_450.jpg" alt="Diego3"
             width="300" height="400">
    </div>
</div>

<!-- ------------------------------------------------------------------------------------------------------------ -->

<div id="accordion2" class="accordion">
    <h2>Accordion using the < script type="text/x-magento-init" > ... < /script ></h2>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Diego</h4>
        </div>
    </div>
    <div data-role="content">
        <img src="https://cdn.britannica.com/76/124976-050-E03E50CE/Diego-Maradona-1986.jpg" alt="Diego" width="300"
             height="400">
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Armando</h4>
        </div>
    </div>
    <div data-role="content">
        <img
            src="https://conteudo.imguol.com.br/c/esporte/2e/2020/04/29/maradona-na-conquista-da-copa-do-mundo-fifa-de-1986-apos-o-episodio-da-la-mano-de-dios-1588180936935_v2_450x600.jpg"
            alt="Diego2" width="300" height="400">
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Maradona</h4>
        </div>
    </div>
    <div data-role="content">
        <img src="https://www.telam.com.ar/thumbs/bluesteel/advf/imagenes/2020/11/5fbe9bdadc9bb_450.jpg" alt="Diego3"
             width="300" height="400">
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#accordion2": {
            "accordion": {
            "active": [],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
            }
        }
    }
</script>

<!-- ------------------------------------------------------------------------------------------------------------ -->

<div data-mage-init='{"sticky":{}}'></div>
