<!-- OPCION 1 -->
<div id="accordion" data-mage-init='{
        "accordion":{
            "active": [0, 1, 2],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
  <h2>Esto es un acordeón pa, clickeá en los títulos para expandir o contraer las secciones</h2>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Parte 1</h4>
    </div>
  </div>
  <div data-role="content">
    Con permiso via a dentrar</br>
    Aunque no soy convidao,</br>
    Pero en mi pago, un asao</br>
    No es de naides y es de todos.</br>
    Yo via cantar a mi modo</br>
    Después que haiga churrasquiao.</div>

  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Parte 2</h4>
    </div>
  </div>
  <div data-role="content">
    No tengo dios pa pedir</br>
    Cuartiada en esta ocasión,</br>
    Ni puedo pedir perdón</br>
    Si entuavía no hei faltao;</br>
    Veré cuando haiga acabao,</br>
    Pero ésa es otra cuestión.</div>

  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Parte 3</h4>
    </div>
  </div>
  <div data-role="content">
    Yo sé que muchos dirán</br>
    Que peco de atrevimiento</br>
    Si largo mi pensamiento</br>
    Pal rumbo que ya elegí,</br>
    Pero siempre he sido ansi:</br>
    Galopiador contra el viento.</div>
</div>

<!-- OPCION 2 -->
<!-- <div id="accordion">
  <h2>Esto es un acordeón pa, clickeá en los títulos para expandir o contraer las secciones</h2>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Parte 1</h4>
    </div>
  </div>
  <div data-role="content">
    Con permiso via a dentrar</br>
    Aunque no soy convidao,</br>
    Pero en mi pago, un asao</br>
    No es de naides y es de todos.</br>
    Yo via cantar a mi modo</br>
    Después que haiga churrasquiao.</div>

  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Parte 2</h4>
    </div>
  </div>
  <div data-role="content">
    No tengo dios pa pedir</br>
    Cuartiada en esta ocasión,</br>
    Ni puedo pedir perdón</br>
    Si entuavía no hei faltao;</br>
    Veré cuando haiga acabao,</br>
    Pero ésa es otra cuestión.
  </div>

  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Parte 3</h4>
    </div>
  </div>
  <div data-role="content">
    Yo sé que muchos dirán</br>
    Que peco de atrevimiento</br>
    Si largo mi pensamiento</br>
    Pal rumbo que ya elegí,</br>
    Pero siempre he sido ansi:</br>
    Galopiador contra el viento.
  </div>
</div>

<script>
  require([
    'jquery',
    'accordion'
  ], function($) {
    $("#accordion").accordion();
  });
</script> -->